version: 2
updates:
  # Enable version updates for python
  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 20
    cooldown-period: 15 # Wait 15 days after release before opening a PR
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      # so it's compatible with docker tags
      separator: "-"